import random

class NLPTranslator:
    """
    Comprehensive NLP Translator for animal sounds to human language.
    Supports multiple animals with all emotion states and varied responses.
    """
    
    def __init__(self):
        # Comprehensive animal-emotion-translation mappings
        self.mappings = {
            # ============ DOGS ============
            "Dog": {
                "Happy": [
                    "I love you so much!",
                    "Play with me! Let's go!",
                    "This is the best day ever!",
                    "Woof! Life is wonderful!",
                    "Can we go for a walk? Please please please!",
                    "You're home! I missed you so much!",
                    "Belly rubs are the best thing ever!",
                    "Let's run and play together!",
                    "I'm so excited to see you!",
                    "Yes yes yes! Treat time!",
                    "I love going outside with you!",
                    "Throw the ball! I'll bring it back!",
                ],
                "Angry": [
                    "Back off right now!",
                    "I'm warning you, stay away!",
                    "Grrr, get out of here!",
                    "Stay away from my human!",
                    "Don't come any closer!",
                    "I'll protect my territory!",
                    "This is MY house!",
                    "You're not welcome here!",
                    "I'm not playing around!",
                    "Leave us alone!",
                ],
                "Sad": [
                    "I miss you so much...",
                    "Where did you go?",
                    "I'm so lonely...",
                    "Please don't leave me alone.",
                    "Why does the rain make me feel this way?",
                    "I just want to cuddle with you.",
                    "Come back soon, okay?",
                    "The house feels empty without you.",
                    "I've been waiting by the door all day.",
                    "Did I do something wrong?",
                ],
                "Hungry": [
                    "Feed me! I'm starving!",
                    "Is that bacon I smell?",
                    "I'm so hungry I could eat everything!",
                    "My bowl has been empty forever!",
                    "What are you eating? Can I have some?",
                    "Treat time? Please?",
                    "The food bag is right there, you know...",
                    "I'll do any trick for a snack!",
                    "Dinner was 2 hours ago, feels like 2 days!",
                    "I'm wasting away here!",
                ],
                "Pain": [
                    "Ouch, that really hurts.",
                    "Help me, please!",
                    "I'm not feeling well...",
                    "Something is wrong with my paw.",
                    "I think I need to see the vet.",
                    "Please be gentle with me.",
                    "It hurts when I walk.",
                    "I don't want to play right now...",
                    "Something's not right...",
                    "Can you make it better?",
                ],
                "Excited": [
                    "OH BOY OH BOY OH BOY!",
                    "Is it walk time?! IS IT?!",
                    "CAR RIDE! I LOVE CAR RIDES!",
                    "NEW PERSON! New person to love!",
                    "I can't contain my happiness!",
                    "My tail won't stop wagging!",
                    "This is the greatest moment of my life!",
                    "SQUIRREL! Did you see that SQUIRREL?!",
                    "The door is opening! THE DOOR!",
                    "Everything is amazing right now!",
                ],
                "Scared": [
                    "What was that noise?!",
                    "I don't like thunder...",
                    "The fireworks are too loud!",
                    "Can I hide under the bed?",
                    "Please stay close to me.",
                    "I need protection!",
                    "That thing is scary!",
                    "I don't want to be alone!",
                    "Hold me, I'm frightened!",
                    "Make the scary thing go away!",
                ],
                "Curious": [
                    "What's that over there?",
                    "I need to sniff everything!",
                    "Something interesting is happening!",
                    "Let me investigate this!",
                    "What are you doing? Can I help?",
                    "New smell! Must explore!",
                    "What's in that bag?",
                    "I've never seen this before!",
                    "Tell me more about this thing!",
                    "This requires further sniffing...",
                ],
                "Playful": [
                    "Catch me if you can!",
                    "Let's play tug of war!",
                    "I got the zoomies!",
                    "Chase me! Chase me!",
                    "Ready, set, PLAY!",
                    "The toy! Throw the toy!",
                    "I'm gonna getcha!",
                    "Play bow! Let's go!",
                    "Round and round I go!",
                    "You can't catch me!",
                ],
            },
            
            # ============ CATS ============
            "Cat": {
                "Happy": [
                    "Purr... everything is perfect.",
                    "You may pet me now, human.",
                    "I suppose you're acceptable.",
                    "This sunny spot is absolutely divine.",
                    "Finally, you understand my worth.",
                    "I am content with your service.",
                    "Purring intensifies... don't stop petting.",
                    "Yes, this is satisfactory.",
                    "You've earned my approval today.",
                    "The perfect temperature, the perfect spot.",
                ],
                "Angry": [
                    "Hiss! Don't you dare touch me!",
                    "I will scratch you without hesitation!",
                    "Leave me be, peasant!",
                    "How dare you disturb my royal nap!",
                    "You'll regret that decision!",
                    "One more step and feel my claws!",
                    "My patience has limits!",
                    "You have been warned!",
                    "I demand space immediately!",
                    "Unacceptable! Completely unacceptable!",
                ],
                "Sad": [
                    "My bowl is empty again...",
                    "Why is the door closed?",
                    "*Sigh* Nobody understands me.",
                    "No one appreciates my presence.",
                    "The red dot... it escaped again.",
                    "You've been gone too long.",
                    "I stared out the window for hours...",
                    "The other cat got more attention.",
                    "My favorite sleeping spot is occupied.",
                    "Life is full of disappointments.",
                ],
                "Hungry": [
                    "Feed me now, servant!",
                    "Meow! FOOD! NOW!",
                    "I can see the bottom of my bowl!",
                    "This is unacceptable service!",
                    "Are you deaf? I said FOOD!",
                    "I'm wasting away before your eyes!",
                    "You call this a portion?",
                    "The audacity of an empty bowl!",
                    "Five more minutes is too long to wait!",
                    "My breakfast is 5 minutes late!",
                ],
                "Pain": [
                    "Hiss... something is wrong.",
                    "It hurts... stay away.",
                    "Don't touch that spot.",
                    "I need to hide somewhere dark.",
                    "Leave me alone, I'm unwell.",
                    "Please help me, quietly.",
                    "I don't feel like myself.",
                    "Something's not right inside.",
                    "I need rest and silence.",
                    "Be very gentle with me.",
                ],
                "Excited": [
                    "Is that the treat bag?!",
                    "BIRD! There's a BIRD!",
                    "3 AM is the perfect time to run!",
                    "The laser dot! It's back!",
                    "Something is moving under the blanket!",
                    "My hunting instincts are tingling!",
                    "New box! MUST SIT IN BOX!",
                    "The crinkly toy! Where is it?!",
                    "Attack mode: ACTIVATED!",
                    "I see something that needs pouncing!",
                ],
                "Scared": [
                    "What is that loud thing?!",
                    "The vacuum cleaner is out!",
                    "I must hide immediately!",
                    "Under the bed is safe...",
                    "That stranger is suspicious!",
                    "The cucumber... it appeared from nowhere!",
                    "Too many sudden movements!",
                    "I need my safe space NOW!",
                    "My ears are flat for a reason!",
                    "Do not bring that thing near me!",
                ],
                "Curious": [
                    "What is this new object?",
                    "I must push this off the table.",
                    "This requires investigation.",
                    "Why is the bathroom door closed?",
                    "Let me inspect your belongings.",
                    "If I fit, I sit... let me check.",
                    "New bag? Must explore inside.",
                    "What are you looking at on that screen?",
                    "Something moved in the grass!",
                    "I've never seen this before...",
                ],
                "Demanding": [
                    "Pay attention to me NOW!",
                    "Open this door immediately!",
                    "I want the wet food, not this!",
                    "Pet me! No, stop! Pet me again!",
                    "Let me outside! No, inside! Outside!",
                    "You're in my spot. Move.",
                    "I require entertainment!",
                    "This is MY chair now!",
                    "Wake up! It's food time!",
                    "Your laptop is less important than me!",
                ],
            },
            
            # ============ COWS ============
            "Cow": {
                "Happy": [
                    "Moo! Life is good in the pasture!",
                    "This grass is absolutely delicious!",
                    "The sunshine feels wonderful today!",
                    "Moo! I love my herd!",
                    "Perfect weather for grazing!",
                    "Another beautiful day in the field!",
                    "The farmer brought fresh hay!",
                    "Rolling in the grass feels amazing!",
                    "Peaceful days are the best days!",
                    "This clover patch is perfect!",
                ],
                "Angry": [
                    "Stay away from my calf!",
                    "Moo! Step back now!",
                    "Don't push me around!",
                    "I'm bigger than you, remember!",
                    "Quit bothering me!",
                    "This is MY grazing spot!",
                    "You're in my way!",
                    "I won't be herded right now!",
                    "Stop poking me!",
                    "I'm not moving!",
                ],
                "Sad": [
                    "The barn feels empty today...",
                    "I miss the warm sunshine.",
                    "Where did my herd go?",
                    "Moo... I'm all alone.",
                    "The pasture isn't the same anymore.",
                    "I feel so tired and lonely.",
                    "Rain again... so gloomy.",
                    "My calf has grown up and left.",
                    "I miss my old barn friend.",
                    "The grass doesn't taste as good today.",
                ],
                "Hungry": [
                    "More hay, please!",
                    "Moo! When is feeding time?",
                    "The pasture needs fresh grass!",
                    "I could eat all day long!",
                    "Got any grain for me?",
                    "My four stomachs are rumbling!",
                    "This section is all grazed already!",
                    "Fresh grass, please!",
                    "The trough is empty!",
                    "I need more to chew on!",
                ],
                "Pain": [
                    "Something hurts, farmer...",
                    "Moo... I need help.",
                    "My leg isn't working right.",
                    "Please call the vet.",
                    "I don't feel well at all.",
                    "It's hard to walk today.",
                    "Something's wrong with my hoof.",
                    "I need to lie down...",
                    "Please be gentle with me.",
                    "I'm not up for walking today.",
                ],
                "Calm": [
                    "Just grazing peacefully...",
                    "Life is simple and good.",
                    "Chewing my cud contentedly.",
                    "The breeze is lovely.",
                    "All is well in the meadow.",
                    "No worries, just grass.",
                    "Perfect peaceful afternoon.",
                    "Moo... tranquil thoughts.",
                    "Watching the clouds drift by.",
                    "Everything is as it should be.",
                ],
            },
            
            # ============ LIONS ============
            "Lion": {
                "Happy": [
                    "ROAR! I am the king of all!",
                    "The pride is strong today!",
                    "Life is glorious in my kingdom!",
                    "The hunt was magnificently successful!",
                    "Surveying my domain brings me joy!",
                    "The savanna is peaceful today!",
                    "My mane looks particularly majestic!",
                    "The pride respects my leadership!",
                    "Another day of ruling supreme!",
                    "All is well in my territory!",
                ],
                "Angry": [
                    "ROAR! Leave my territory NOW!",
                    "You dare challenge ME?!",
                    "I will defend my pride to the death!",
                    "Stay away, foolish intruder!",
                    "ROAR! Feel my wrath!",
                    "You've made a grave mistake!",
                    "No one threatens my family!",
                    "This is your final warning!",
                    "I am the apex predator here!",
                    "You will regret this intrusion!",
                ],
                "Sad": [
                    "The savanna feels lonely today...",
                    "I miss the old times.",
                    "My pride seems distant.",
                    "Even kings feel sorrow.",
                    "The sunset brings melancholy.",
                    "Another great lion has fallen.",
                    "The drought has been hard on us all.",
                    "I grow weary of fighting.",
                    "My strength isn't what it was.",
                    "The responsibilities weigh heavy.",
                ],
                "Hungry": [
                    "Time for the hunt!",
                    "I hunger for the chase!",
                    "The prey will not escape me!",
                    "My stomach demands tribute!",
                    "Where is my feast?!",
                    "The king must eat well!",
                    "Hunting instincts are calling!",
                    "The pride needs to eat!",
                    "Let the hunt begin!",
                    "I smell prey on the wind!",
                ],
                "Pain": [
                    "Even kings feel pain...",
                    "I need rest and recovery.",
                    "The battle wounds sting.",
                    "I'm not as strong today.",
                    "Age catches up with everyone.",
                    "I must hide my weakness.",
                    "The fight took its toll.",
                    "My old injuries ache.",
                    "Rest is needed for now.",
                    "This too shall pass.",
                ],
                "Proud": [
                    "Behold my magnificent mane!",
                    "I am the ruler of all I survey!",
                    "None can match my power!",
                    "The pride follows my lead!",
                    "I am royalty incarnate!",
                    "This land belongs to ME!",
                    "My roar echoes across the plains!",
                    "I am the undisputed king!",
                    "Witnesses my grandeur!",
                    "Born to rule, destined to reign!",
                ],
            },
            
            # ============ BIRDS ============
            "Bird": {
                "Happy": [
                    "Tweet tweet! Beautiful day to fly!",
                    "The wind beneath my wings is perfect!",
                    "Time to sing my heart out!",
                    "Found the perfect branch!",
                    "Chirp chirp! Life is wonderful!",
                    "The sunrise is magnificent!",
                    "My feathers look fantastic today!",
                    "Flying free feels amazing!",
                    "The flock is together and happy!",
                    "What a perfect day for singing!",
                ],
                "Angry": [
                    "Squawk! Stay away from my nest!",
                    "Don't touch my eggs!",
                    "This is MY territory!",
                    "I'll peck you if you come closer!",
                    "Warning: aggressive bird incoming!",
                    "Get away from my mate!",
                    "This tree belongs to ME!",
                    "I will dive-bomb you!",
                    "Back off, NOW!",
                    "You've been warned!",
                ],
                "Sad": [
                    "My nest feels empty...",
                    "The flock left without me.",
                    "Where did summer go?",
                    "I miss my mate terribly.",
                    "The cage is so small...",
                    "I want to fly free...",
                    "My eggs didn't hatch...",
                    "The migration was too hard.",
                    "I can't find my way home.",
                    "The song has left my heart.",
                ],
                "Hungry": [
                    "Worms! I need worms!",
                    "Is that a seed? MINE!",
                    "Feed the birdie!",
                    "My feeder is empty again!",
                    "Tweet! Time for breakfast!",
                    "I'm starving up here!",
                    "The ground has no bugs!",
                    "Where are all the berries?",
                    "I need to eat before flying!",
                    "Food, please! Chirp chirp!",
                ],
                "Pain": [
                    "My wing hurts badly...",
                    "I can't fly properly.",
                    "Something is stuck in my beak.",
                    "Please help me, human.",
                    "I need to rest my wing.",
                    "Flying is painful right now.",
                    "I think I'm injured.",
                    "I can't perch properly.",
                    "Something's very wrong...",
                    "I need care and rest.",
                ],
                "Singing": [
                    "La la la, it's a beautiful morning!",
                    "Listen to my beautiful melody!",
                    "Tweet tweet tweet, hear my song!",
                    "I'm the best singer in this tree!",
                    "My song attracts all the mates!",
                    "Dawn chorus time! Sing along!",
                    "This is my territory and I'm proud!",
                    "Trilling my heart out!",
                    "Nature's musician at your service!",
                    "Can you appreciate my vocal range?",
                ],
                "Alert": [
                    "DANGER! Predator spotted!",
                    "Everyone, fly away NOW!",
                    "Cat! CAT! Watch out!",
                    "Something's coming this way!",
                    "Hide the chicks immediately!",
                    "Alarm call! Alarm call!",
                    "Take cover in the bushes!",
                    "This is not a drill! FLY!",
                    "Hawk circling above!",
                    "Scatter! Everyone scatter!",
                ],
            },
            
            # ============ HORSES ============
            "Horse": {
                "Happy": [
                    "Neigh! Let's run free!",
                    "This meadow is paradise!",
                    "Galloping feels absolutely amazing!",
                    "The herd is together and strong!",
                    "Brushing time! I love this!",
                    "Fresh hay, best day ever!",
                    "Rolling in the grass is the best!",
                    "The rider and I are in sync!",
                    "Freedom in the open field!",
                    "Life is good in the stable!",
                ],
                "Angry": [
                    "Back off or I'll kick!",
                    "Don't pull my mane!",
                    "This saddle is so uncomfortable!",
                    "I've had enough riding for today!",
                    "Neigh! Leave me alone!",
                    "Don't approach from behind!",
                    "I'm not going in that trailer!",
                    "Stop yanking the reins!",
                    "I refuse to jump that!",
                    "My patience has run out!",
                ],
                "Sad": [
                    "The stable feels so lonely...",
                    "I miss running in the fields.",
                    "My friend was taken away.",
                    "Why am I always inside?",
                    "Neigh... I'm so tired.",
                    "I want my old pasture back.",
                    "Nobody visits me anymore.",
                    "The barn is too quiet.",
                    "I miss my herd family.",
                    "Rainy days make me gloomy.",
                ],
                "Hungry": [
                    "Oats! I smell oats!",
                    "More hay in my trough please!",
                    "Carrots would be wonderful!",
                    "When is feeding time already?",
                    "I could eat an entire field!",
                    "The grass looks delicious!",
                    "Apple treats, please!",
                    "My stomach is rumbling!",
                    "Is that a sugar cube?!",
                    "Feed time is my favorite time!",
                ],
                "Pain": [
                    "My hoof hurts terribly.",
                    "The bit is much too tight.",
                    "Something's wrong with my leg.",
                    "I need the farrier urgently.",
                    "Please be very gentle...",
                    "I'm limping and it hurts.",
                    "My back is sore from riding.",
                    "These shoes don't fit right.",
                    "I need rest and care.",
                    "Don't make me run today.",
                ],
                "Excited": [
                    "We're going out! FINALLY!",
                    "Race time! Let's GO!",
                    "Other horses! I see horses!",
                    "The gate is opening!",
                    "Time to show off my speed!",
                    "Adventure awaits us!",
                    "I can run forever today!",
                    "The trail ride begins!",
                    "So much energy to burn!",
                    "Let's gallop together!",
                ],
                "Calm": [
                    "Peaceful grazing time.",
                    "The sun feels wonderful.",
                    "Just relaxing in the pasture.",
                    "All is well in my world.",
                    "Quiet afternoon munching.",
                    "Gentle breeze, soft grass.",
                    "No worries today.",
                    "Standing in the shade contentedly.",
                    "Life is simple and good.",
                    "Perfect day for rest.",
                ],
            },
            
            # ============ ELEPHANTS ============
            "Elephant": {
                "Happy": [
                    "Trumpet of joy! Life is wonderful!",
                    "My herd is with me!",
                    "The watering hole is perfect!",
                    "Playing with mud is the best!",
                    "My family makes me happy!",
                    "Today is a good day to forage!",
                    "The matriarch leads us well!",
                    "Trunk high in celebration!",
                    "Baby elephants bring such joy!",
                    "Peaceful grazing with my family!",
                ],
                "Angry": [
                    "Stay away from my calf!",
                    "Ears out! I mean business!",
                    "Trumpet of warning! BACK OFF!",
                    "I will charge if you come closer!",
                    "Don't threaten my herd!",
                    "Leave this territory NOW!",
                    "I'm much bigger than you!",
                    "Final warning! Move away!",
                    "My memory is long and I won't forget!",
                    "You're testing my patience!",
                ],
                "Sad": [
                    "I remember those we've lost...",
                    "The drought makes life so hard.",
                    "My herd member has passed.",
                    "I return to visit old memories.",
                    "The watering hole is drying up.",
                    "We've walked so far...",
                    "I miss the old feeding grounds.",
                    "Mourning comes naturally to elephants.",
                    "The journey has been long.",
                    "My heart is heavy today.",
                ],
                "Hungry": [
                    "Time to find more trees!",
                    "I need 300 pounds of food today!",
                    "The branches here are picked clean.",
                    "Fruit trees, where are you?",
                    "My trunk seeks more vegetation!",
                    "The herd must keep moving to eat.",
                    "Water and food are essential!",
                    "These leaves look delicious!",
                    "Stripping bark is hard work!",
                    "Lead us to better grazing!",
                ],
                "Pain": [
                    "My feet are sore from walking.",
                    "Old injuries trouble me.",
                    "The hot ground burns.",
                    "I need to rest my legs.",
                    "Age catches up with us all.",
                    "The tusk is causing pain.",
                    "Walking is harder today.",
                    "My old bones ache.",
                    "I need cooling mud.",
                    "Please, let me rest awhile.",
                ],
            },
            
            # ============ SHEEP ============
            "Sheep": {
                "Happy": [
                    "Baa! The grass is wonderful!",
                    "Grazing with my flock is bliss!",
                    "The shepherd keeps us safe!",
                    "Woolly and warm, life is good!",
                    "Spring lambs make me joyful!",
                    "This meadow is perfect!",
                    "The sun feels great on my wool!",
                    "Flock together, stay together!",
                    "Happy baa-ing all around!",
                    "Rolling hills are my paradise!",
                ],
                "Scared": [
                    "BAA! WOLF! I see a wolf!",
                    "Stay together, everyone!",
                    "Where's the shepherd?!",
                    "Something's not right!",
                    "That sound was terrifying!",
                    "Hide behind the others!",
                    "The dog is scaring me!",
                    "Run to the barn, quickly!",
                    "I don't like storms!",
                    "Too many strangers around!",
                ],
                "Hungry": [
                    "Baa! Need more grass!",
                    "This patch is all eaten!",
                    "When do we move to fresh pasture?",
                    "More hay, please!",
                    "I'm always ready to graze!",
                    "The lambs need to eat!",
                    "Lead us to greener fields!",
                    "Hungry sheep are unhappy sheep!",
                    "More clover would be nice!",
                    "My four stomachs need filling!",
                ],
            },
            
            # ============ GOATS ============
            "Goat": {
                "Happy": [
                    "Life is great! I'm climbing!",
                    "This rock is the perfect perch!",
                    "Maa! I love adventures!",
                    "Exploring everywhere is fun!",
                    "I can climb anything!",
                    "Head butting is so entertaining!",
                    "Fresh vegetation tastes amazing!",
                    "The farmyard is my playground!",
                    "Being stubborn is my specialty!",
                    "Watch me balance on this!",
                ],
                "Mischievous": [
                    "I'm gonna eat that shirt!",
                    "Your garden looks delicious!",
                    "What's behind this fence?",
                    "I escaped AGAIN! Catch me!",
                    "Everything is edible to me!",
                    "Head butt incoming!",
                    "Your bucket is now MY bucket!",
                    "I'll chew through anything!",
                    "Rules are for other animals!",
                    "That laundry looks tasty!",
                ],
                "Angry": [
                    "Don't test me, I head butt!",
                    "Back away slowly!",
                    "My horns aren't just for show!",
                    "This is MY spot!",
                    "I warned you!",
                    "Goat rage activated!",
                    "Don't corner a goat!",
                    "I'm tougher than I look!",
                    "Mess with me, feel the horns!",
                    "You think you can push me?",
                ],
            },
            
            # ============ PIGS ============
            "Pig": {
                "Happy": [
                    "Oink oink! Mud bath time!",
                    "Rolling in mud is heaven!",
                    "Snout to the ground, life is good!",
                    "Food is coming, I can smell it!",
                    "The trough is full! Joy!",
                    "Belly scratches are the best!",
                    "Wallowing in cool mud!",
                    "Napping in the shade!",
                    "Piglet cuddles are wonderful!",
                    "This is the life!",
                ],
                "Hungry": [
                    "OINK! Where's the food?!",
                    "I smell something edible!",
                    "Scraps! Bring me scraps!",
                    "The trough is empty!",
                    "I could eat all day!",
                    "Is that slop I smell?",
                    "Feeding time is the best time!",
                    "More food, always more food!",
                    "My snout guides me to meals!",
                    "Never enough to eat!",
                ],
                "Curious": [
                    "What's buried here?",
                    "Let me dig and find out!",
                    "Something interesting is hidden!",
                    "My snout knows secrets!",
                    "Sniff sniff... what's that?",
                    "There's treasure underground!",
                    "Must investigate everything!",
                    "What are you hiding?",
                    "Rooting around is my passion!",
                    "I can find anything with this snout!",
                ],
            },
            
            # ============ CHICKENS ============
            "Chicken": {
                "Happy": [
                    "Bawk bawk! Found a bug!",
                    "Cluck cluck, life is good!",
                    "Dust bath time!",
                    "Freshly laid egg, I'm proud!",
                    "Scratching in the dirt is fun!",
                    "The coop is cozy today!",
                    "Grain time is the best time!",
                    "My feathers look fabulous!",
                    "Roosting with friends!",
                    "The sun feels wonderful!",
                ],
                "Scared": [
                    "BAWK! FOX! HAWK!",
                    "Run to the coop!",
                    "Hide under something!",
                    "The sky is dangerous!",
                    "Alarm! Alarm! Predator!",
                    "Protect the chicks!",
                    "Something's coming!",
                    "Panic clucking intensifies!",
                    "Into the henhouse, quick!",
                    "We're not safe out here!",
                ],
                "Bossy": [
                    "I'm the top hen here!",
                    "Move aside for me!",
                    "Pecking order, remember it!",
                    "That's MY roosting spot!",
                    "I eat first, always!",
                    "This is how we do things!",
                    "The rooster answers to ME!",
                    "New chickens, know your place!",
                    "I run this coop!",
                    "Fall in line!",
                ],
            },
            
            # ============ DUCKS ============
            "Duck": {
                "Happy": [
                    "Quack quack! Water is perfect!",
                    "Swimming is my favorite thing!",
                    "Bread crumbs! Amazing!",
                    "Paddling around contentedly!",
                    "My waterproof feathers are the best!",
                    "Ducklings in a row, so proud!",
                    "The pond is my paradise!",
                    "Splashing brings me joy!",
                    "Preening time, looking good!",
                    "Diving for snacks!",
                ],
                "Demanding": [
                    "Quack! More bread!",
                    "You're holding out on me!",
                    "This pond belongs to US!",
                    "Share the food equally!",
                    "I know you have more in that bag!",
                    "Quack louder until fed!",
                    "Don't walk away, human!",
                    "We expect daily feeding!",
                    "The quacking continues!",
                    "More snacks or face the quacks!",
                ],
            },

            # ============ MONKEY ============
            "Monkey": {
                "Happy": [
                    "Oo oo ah ah! Tree swinging fun!",
                    "Found a banana! Best day!",
                    "Grooming buddies make life good!",
                    "Playing in the trees!",
                    "Chatter chatter, everyone's happy!",
                    "Sunshine and fruit, perfect combo!",
                    "Jumping from branch to branch!",
                    "Family time is the best!",
                    "This fruit is delicious!",
                    "Rainforest life is awesome!",
                ],
                "Mischievous": [
                    "I stole something shiny!",
                    "Your food is now MY food!",
                    "Catch me if you can!",
                    "What does this button do?",
                    "Everything must be investigated!",
                    "I'll take that, thank you!",
                    "Chaos is my specialty!",
                    "Nothing is safe from me!",
                    "Your hat looks better on ME!",
                    "Monkey see, monkey take!",
                ],
                "Angry": [
                    "SCREECH! Back off!",
                    "Don't mess with our troop!",
                    "Teeth bared, I'm warning you!",
                    "This territory is OURS!",
                    "Threatening posture activated!",
                    "You took my food!",
                    "Stay away from the babies!",
                    "I'm the dominant one here!",
                    "Fight me if you dare!",
                    "Last warning, leave now!",
                ],
            },
            
            # ============ PARROT ============
            "Parrot": {
                "Happy": [
                    "Pretty bird! Pretty bird!",
                    "Hello! Hello! HELLO!",
                    "Want a cracker? I do!",
                    "Stepping up, stepping up!",
                    "Preening makes me beautiful!",
                    "Whistling my favorite tune!",
                    "Head scratches are AMAZING!",
                    "Flying around the room!",
                    "My colors are magnificent!",
                    "Dance party! Bobbing head!",
                ],
                "Chatty": [
                    "Let me tell you EVERYTHING!",
                    "Repeat after me! REPEAT!",
                    "I know 50 words!",
                    "HELLO! Goodbye! Hello again!",
                    "What are you doing? What?",
                    "I can talk ALL day!",
                    "Pay attention to me!",
                    "Want to hear a song?",
                    "Words words words!",
                    "I'm the smartest bird!",
                ],
                "Angry": [
                    "SQUAWK! Step back!",
                    "I will bite!",
                    "My beak is a weapon!",
                    "Crest up! I'm mad!",
                    "Don't put me in the cage!",
                    "I'm screaming for ATTENTION!",
                    "You're ignoring me! SQUAWK!",
                    "Warning screech incoming!",
                    "I am DISPLEASED!",
                    "Feathers ruffled in anger!",
                ],
            },
            
            # ============ WOLF ============
            "Wolf": {
                "Happy": [
                    "AWOOO! Pack is together!",
                    "The hunt was successful!",
                    "Playing with pack mates!",
                    "Howling our joy to the moon!",
                    "The territory is secure!",
                    "Pups are healthy and strong!",
                    "Running free in the wild!",
                    "Full belly, happy wolf!",
                    "Pack bonds are everything!",
                    "Freedom under the stars!",
                ],
                "Aggressive": [
                    "GROWL! This is our territory!",
                    "The pack defends together!",
                    "Intruder detected!",
                    "Warning snarl incoming!",
                    "Stay away from our den!",
                    "Alpha says: LEAVE NOW!",
                    "We hunt, we defend!",
                    "Teeth bared, last warning!",
                    "The pack will attack!",
                    "You've been warned, outsider!",
                ],
                "Lonely": [
                    "My pack... where are they?",
                    "Howling into the darkness alone...",
                    "The lone wolf's burden...",
                    "I miss my pack mates.",
                    "Wandering without purpose.",
                    "A wolf needs their pack.",
                    "The silence is deafening.",
                    "Will anyone answer my call?",
                    "Separated and searching...",
                    "The moon brings loneliness.",
                ],
            },
        }
        
        # Default responses for any unrecognized input
        self.default_responses = [
            "I'm trying to communicate with you!",
            "Can you understand what I'm saying?",
            "Hello, human friend!",
            "I have something important to tell you!",
            "Listen closely to my message!",
            "Pay attention to my sounds!",
            "I'm expressing myself the best I can!",
            "Every sound has meaning!",
            "Animals have feelings too!",
            "We speak in our own way!",
        ]
        
        # Unknown animal default messages
        self.unknown_animal_responses = {
            "Happy": ["I'm feeling great today!", "Life is good!", "Everything is wonderful!"],
            "Angry": ["Back off! I'm upset!", "Leave me alone!", "I'm warning you!"],
            "Sad": ["I'm feeling down...", "Something's not right.", "I'm a bit lonely."],
            "Hungry": ["I'm so hungry!", "Food please!", "Time to eat!"],
            "Pain": ["I'm not feeling well.", "Something hurts.", "I need help."],
            "Excited": ["So much excitement!", "This is amazing!", "I can't contain myself!"],
            "Scared": ["I'm frightened!", "Help, I'm scared!", "Something scary is near!"],
            "Curious": ["What's that over there?", "Let me investigate!", "I'm intrigued!"],
        }

    def translate(self, animal, emotion):
        """
        Translate animal + emotion to a natural language sentence.
        
        Args:
            animal: The detected animal type
            emotion: The detected emotion
            
        Returns:
            A natural language translation string
        """
        try:
            # Try exact match first
            animal_mappings = self.mappings.get(animal, {})
            if animal_mappings and emotion in animal_mappings:
                return random.choice(animal_mappings[emotion])
            
            # If emotion not found for animal, try similar emotions
            similar_emotions = {
                "Excited": ["Happy", "Playful"],
                "Playful": ["Happy", "Excited"],
                "Calm": ["Happy"],
                "Demanding": ["Hungry", "Angry"],
                "Alert": ["Scared", "Angry"],
                "Mischievous": ["Playful", "Happy"],
                "Proud": ["Happy"],
                "Chatty": ["Happy", "Excited"],
                "Aggressive": ["Angry"],
                "Lonely": ["Sad"],
                "Bossy": ["Angry", "Demanding"],
                "Singing": ["Happy"],
            }
            
            if emotion in similar_emotions:
                for similar in similar_emotions[emotion]:
                    if similar in animal_mappings:
                        return random.choice(animal_mappings[similar])
            
            # Try unknown animal with specific emotion
            if emotion in self.unknown_animal_responses:
                return random.choice(self.unknown_animal_responses[emotion])
            
            # Final fallback
            return random.choice(self.default_responses)
            
        except Exception as e:
            print(f"Translation error: {e}")
            return "I am an animal with something important to say!"
    
    def get_supported_animals(self):
        """Return list of all supported animals."""
        return list(self.mappings.keys())
    
    def get_supported_emotions(self):
        """Return list of all supported emotions."""
        all_emotions = set()
        for animal_emotions in self.mappings.values():
            all_emotions.update(animal_emotions.keys())
        return sorted(list(all_emotions))
    
    def get_animal_emotions(self, animal):
        """Get all emotions supported for a specific animal."""
        return list(self.mappings.get(animal, {}).keys())

translator = NLPTranslator()
